/*
since we are storing transactions in memory:
    - database.js will be where our transactions are stored
    - a constructor will be used as a 'schema' for the transactions
*/


//initialize constructor
class Transaction {
    //constructor will take payer and points from query params as arguments 
    constructor(payer, points){
        
        //set payer value
        this.payer = payer;
        
        //set points value
        this.points = points;

        //timestamp will be generated by Date object
        this.timestamp = new Date();

    }
}

//Export Transaction to be used in transactionApi controller
module.exports = Transaction; 